version: "3"

services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - "db"
      - "redis"
  db:
    restart: always
    image: postgres:base
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    
  redis:
    image: redis:alpine
                           
volumes:
    db_data:
      external: true     